name: 'DepHell'
description: 'Run DepHell envs'
inputs:
  env:
    description: 'DepHell env to install dependencies and run'
    required: true
    default: 'main'
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
