on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run DepHell
        uses: dephell/dephell_action@v0.0.3
        with:
          dephell-env: main
